// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFr529ADt-V6W4ufeQDlj-vj3DtQ9Ov4o',
    appId: '1:943142922730:web:f68ffd7dcb654952b1aa93',
    messagingSenderId: '943142922730',
    projectId: 'marcaya-b00bf',
    authDomain: 'marcaya-b00bf.firebaseapp.com',
    storageBucket: 'marcaya-b00bf.firebasestorage.app',
    measurementId: 'G-7C225NHV34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTubdkHNRaLOhckt_IAvQ64JFNz9K79xs',
    appId: '1:943142922730:android:d26890a7312ba6d6b1aa93',
    messagingSenderId: '943142922730',
    projectId: 'marcaya-b00bf',
    storageBucket: 'marcaya-b00bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbMg1NdjdlEsDNkxbE_DUeUjK9cV5tc0s',
    appId: '1:943142922730:ios:66cefebab23a1a83b1aa93',
    messagingSenderId: '943142922730',
    projectId: 'marcaya-b00bf',
    storageBucket: 'marcaya-b00bf.firebasestorage.app',
    iosBundleId: 'mar',
  );
}
